In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('job_dataset.csv')

In [4]:
df

,job_id,job_title,company,location,job_description,experience,education,salary_lpa,job_type,required_skills
0,JOB809570,Java Developer,IBM,"Nagpur, Maharashtra",We are hiring a Java Developer at IBM in Nagpu...,0-1 years,MCA,6.8,Part-time,"Java, Spring Boot, Hibernate, Microservices, R..."
1,JOB731262,AI Engineer,Infosys,"Pune, Maharashtra",We are hiring a AI Engineer at Infosys in Pune...,5-8 years,BE Computer Engineering,6.8,Part-time,"Python, Machine Learning, Deep Learning, NLP, ..."
2,JOB106814,Data Analyst,Tech Mahindra,"Noida, Uttar Pradesh",We are hiring a Data Analyst at Tech Mahindra ...,0-1 years,MTech Computer Science,7.2,Contract,"SQL, Power BI, Excel, Tableau, Python"
3,JOB452944,NLP Engineer,Persistent Systems,"Bengaluru, Karnataka",We are hiring a NLP Engineer at Persistent Sys...,5-8 years,BCA,12.4,Part-time,"Python, NLP, BERT, Transformers, spaCy, NLTK, ..."
4,JOB865179,Business Analyst,HCLTech,"Hyderabad, Telangana",We are hiring a Business Analyst at HCLTech in...,5-8 years,BSc Data Science,11.2,Contract,"SQL, Power BI, Excel, JIRA, Statistics"
...,...,...,...,...,...,...,...,...,...,...
95,JOB335729,Business Analyst,Fractal Analytics,"Ahmedabad, Gujarat",We are hiring a Business Analyst at Fractal An...,3-6 years,MCA,5.1,Internship,"SQL, Power BI, Excel, JIRA, Statistics"
96,JOB723948,Java Developer,Accenture,"Mumbai, Maharashtra",We are hiring a Java Developer at Accenture in...,2-5 years,BTech Computer Science,9.3,Part-time,"Java, Spring Boot, Hibernate, Microservices, R..."
97,JOB624783,AI Engineer,HCLTech,"Noida, Uttar Pradesh",We are hiring a AI Engineer at HCLTech in Noid...,2-5 years,BSc Computer Science,10.4,Internship,"Python, TensorFlow, NLP, LLM, Docker, Deep Lea..."
98,JOB733039,SQL Developer,Wipro,"Gurugram, Haryana",We are hiring a SQL Developer at Wipro in Guru...,8-12 years,BTech Computer Science,12.8,Internship,"SQL Server, Python, MySQL, PostgreSQL, Databas..."
99,JOB804938,Data Engineer,Tech Mahindra,"Ahmedabad, Gujarat",We are hiring a Data Engineer at Tech Mahindra...,1-3 years,MTech Computer Science,9.4,Full-time,"Python, SQL, ETL, Spark, AWS, Airflow"

In [5]:
df.head()

,job_id,job_title,company,location,job_description,experience,education,salary_lpa,job_type,required_skills
0,JOB809570,Java Developer,IBM,"Nagpur, Maharashtra",We are hiring a Java Developer at IBM in Nagpu...,0-1 years,MCA,6.8,Part-time,"Java, Spring Boot, Hibernate, Microservices, R..."
1,JOB731262,AI Engineer,Infosys,"Pune, Maharashtra",We are hiring a AI Engineer at Infosys in Pune...,5-8 years,BE Computer Engineering,6.8,Part-time,"Python, Machine Learning, Deep Learning, NLP, ..."
2,JOB106814,Data Analyst,Tech Mahindra,"Noida, Uttar Pradesh",We are hiring a Data Analyst at Tech Mahindra ...,0-1 years,MTech Computer Science,7.2,Contract,"SQL, Power BI, Excel, Tableau, Python"
3,JOB452944,NLP Engineer,Persistent Systems,"Bengaluru, Karnataka",We are hiring a NLP Engineer at Persistent Sys...,5-8 years,BCA,12.4,Part-time,"Python, NLP, BERT, Transformers, spaCy, NLTK, ..."
4,JOB865179,Business Analyst,HCLTech,"Hyderabad, Telangana",We are hiring a Business Analyst at HCLTech in...,5-8 years,BSc Data Science,11.2,Contract,"SQL, Power BI, Excel, JIRA, Statistics"

In [6]:
df.tail()

,job_id,job_title,company,location,job_description,experience,education,salary_lpa,job_type,required_skills
95,JOB335729,Business Analyst,Fractal Analytics,"Ahmedabad, Gujarat",We are hiring a Business Analyst at Fractal An...,3-6 years,MCA,5.1,Internship,"SQL, Power BI, Excel, JIRA, Statistics"
96,JOB723948,Java Developer,Accenture,"Mumbai, Maharashtra",We are hiring a Java Developer at Accenture in...,2-5 years,BTech Computer Science,9.3,Part-time,"Java, Spring Boot, Hibernate, Microservices, R..."
97,JOB624783,AI Engineer,HCLTech,"Noida, Uttar Pradesh",We are hiring a AI Engineer at HCLTech in Noid...,2-5 years,BSc Computer Science,10.4,Internship,"Python, TensorFlow, NLP, LLM, Docker, Deep Lea..."
98,JOB733039,SQL Developer,Wipro,"Gurugram, Haryana",We are hiring a SQL Developer at Wipro in Guru...,8-12 years,BTech Computer Science,12.8,Internship,"SQL Server, Python, MySQL, PostgreSQL, Databas..."
99,JOB804938,Data Engineer,Tech Mahindra,"Ahmedabad, Gujarat",We are hiring a Data Engineer at Tech Mahindra...,1-3 years,MTech Computer Science,9.4,Full-time,"Python, SQL, ETL, Spark, AWS, Airflow"

In [9]:
df.sample(10)

,job_id,job_title,company,location,job_description,experience,education,salary_lpa,job_type,required_skills
61,JOB345884,DevOps Engineer,Tech Mahindra,"Bengaluru, Karnataka",We are hiring a DevOps Engineer at Tech Mahind...,5-8 years,Any Graduate,10.5,Full-time,"AWS, Terraform, Docker, Kubernetes, Jenkins, C..."
46,JOB392683,Data Scientist,Mphasis,"Hyderabad, Telangana",We are hiring a Data Scientist at Mphasis in H...,1-3 years,BSc Computer Science,9.3,Full-time,"Python, Pandas, NumPy, Scikit-learn, Machine L..."
62,JOB827659,Data Engineer,Bosch,"Mumbai, Maharashtra",We are hiring a Data Engineer at Bosch in Mumb...,5-8 years,BCA,6.7,Part-time,"Databricks, Azure, Spark, ETL, Python, SQL"
60,JOB359249,Web Developer,Capgemini,"Remote, India",We are hiring a Web Developer at Capgemini in ...,5-8 years,Any Graduate,7.0,Internship,"React, Node.js, JavaScript, MongoDB, HTML, CSS"
82,JOB709805,Cloud Engineer,Deloitte,"Nagpur, Maharashtra",We are hiring a Cloud Engineer at Deloitte in ...,0-1 years,MSc Data Science,4.7,Part-time,"AWS, Azure, Docker, Kubernetes, Terraform, Lin..."
32,JOB539589,DevOps Engineer,HCLTech,"Gurugram, Haryana",We are hiring a DevOps Engineer at HCLTech in ...,3-6 years,MCA,8.7,Full-time,"Docker, Kubernetes, AWS, Jenkins, CI/CD, Linux..."
63,JOB316881,Python Developer,Oracle,"Chennai, Tamil Nadu",We are hiring a Python Developer at Oracle in ...,0-1 years,BSc Data Science,5.3,Internship,"Python, Django, Flask, FastAPI, SQL, Git, REST..."
2,JOB106814,Data Analyst,Tech Mahindra,"Noida, Uttar Pradesh",We are hiring a Data Analyst at Tech Mahindra ...,0-1 years,MTech Computer Science,7.2,Contract,"SQL, Power BI, Excel, Tableau, Python"
55,JOB254511,Web Developer,Tech Mahindra,"Ahmedabad, Gujarat",We are hiring a Web Developer at Tech Mahindra...,1-3 years,BSc Computer Science,8.3,Part-time,"React, Node.js, JavaScript, MongoDB, HTML, CSS"
10,JOB358607,Data Scientist,Amazon,"Chennai, Tamil Nadu",We are hiring a Data Scientist at Amazon in Ch...,1-3 years,Any Graduate,5.1,Part-time,"Python, TensorFlow, Statistics, Pandas, Machin..."

In [10]:
df.shape

(100, 10)

In [11]:
df.columns

Index(['job_id', 'job_title', 'company', 'location', 'job_description',
       'experience', 'education', 'salary_lpa', 'job_type', 'required_skills'],
      dtype='object')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   job_id           100 non-null    object
 1   job_title        100 non-null    object
 2   company          100 non-null    object
 3   location         100 non-null    object
 4   job_description  100 non-null    object
 5   experience       100 non-null    object
 6   education        100 non-null    object
 7   salary_lpa       100 non-null    float64
 8   job_type         100 non-null    object
 9   required_skills  100 non-null    object
dtypes: float64(1), object(9)
memory usage: 7.9+ KB

In [15]:
df.isnull().sum()

job_id             0
job_title          0
company            0
location           0
job_description    0
experience         0
education          0
salary_lpa         0
job_type           0
required_skills    0
dtype: int64

In [16]:
df.duplicated().sum()

np.int64(0)